### ISSUE TITLE
add v0.3.0 to NPM

### ISSUE THREAD

**Issue by 0xf0xx0** [Sv443/Node-Wrap#7]
It seems like you haven't published v0.3.0? My workaround is `cd`ing into the `node_modules` folder and cloning the repo.

**Comment by Sv443** [comment]
I didn't see this issue until now but you really shouldn't be using this project. The code is really bad and breaks compatibility with some libraries. Instead use a process manager like [pm2](https://pm2.keymetrics.io/)
